In [1]:
import pandas as pd

In [4]:
dados = pd.read_csv('train_transaction_clean.csv', sep=';')

In [5]:
dados.head(20)

,isFraud,TransactionDT,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,card6,addr1,addr2,dist1
0,0,86401,29.000,1,2755,404.0,150.0,3.0,102.0,1.0,325.0,87.0,118.50218
1,0,86469,59.000,1,4663,490.0,150.0,2.0,166.0,0.0,330.0,87.0,287.00000
2,0,86499,50.000,1,18132,567.0,150.0,3.0,117.0,0.0,476.0,87.0,118.50218
3,0,86506,50.000,4,4497,514.0,150.0,3.0,102.0,1.0,420.0,87.0,118.50218
4,0,86510,49.000,1,5937,555.0,150.0,2.0,226.0,0.0,272.0,87.0,36.00000
5,0,86522,159.000,1,12308,360.0,150.0,2.0,166.0,0.0,126.0,87.0,0.00000
6,0,86529,422.500,1,12695,490.0,150.0,2.0,226.0,0.0,325.0,87.0,118.50218
7,0,86535,15.000,4,2803,100.0,150.0,2.0,226.0,0.0,337.0,87.0,118.50218
8,0,86536,117.000,1,17399,111.0,150.0,3.0,224.0,0.0,204.0,87.0,19.00000
9,0,86549,75.887,2,16496,352.0,117.0,3.0,134.0,1.0,299.0,87.0,118.50218
10,0,86555,16.495,2,4461,375.0,185.0,3.0,224.0,0.0,299.0,87.0,118.50218
11,0,86564,50.000,1,3786,418.0,150.0,2.0,226.0,0.0,204.0,87.0,118.50218
12,0,86585,40.000,1,12866,303.0,150.0,2.0,226.0,0.0,330.0,87.0,118.50218
13,0,86596,10.500,1,11839,490.0,150.0,2.0,226.0,0.0,226.0,87.0,118.50218
14,0,86618,57.950,1,7055,555.0,150.0,2.0,226.0,0.0,315.0,87.0,3.00000
15,0,86620,30.000,4,1790,555.0,150.0,2.0,226.0,0.0,170.0,87.0,118.50218
16,0,86668,100.000,4,11492,111.0,150.0,3.0,219.0,1.0,204.0,87.0,118.50218
17,0,86725,47.950,1,4663,490.0,150.0,2.0,166.0,0.0,184.0,87.0,5.00000
18,0,86730,186.000,1,7005,111.0,150.0,2.0,226.0,0.0,264.0,87.0,118.50218
19,0,86761,39.000,1,7875,314.0,150.0,3.0,224.0,0.0,299.0,87.0,0.00000

### Formula do Scaling

In [6]:
data = dados
data = (data - data.min()) / (data.max() - data.min())

In [7]:
data.head(10)

,isFraud,TransactionDT,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,card6,addr1,addr2,dist1
0,0.0,0.000000,0.000900,0.00,0.100885,0.608,0.381679,0.666667,0.014599,1.0,0.511364,0.836957,0.011521
1,0.0,0.000004,0.001840,0.00,0.210566,0.780,0.381679,0.333333,0.481752,0.0,0.522727,0.836957,0.027902
2,0.0,0.000006,0.001558,0.00,0.984824,0.934,0.381679,0.666667,0.124088,0.0,0.854545,0.836957,0.011521
3,0.0,0.000007,0.001558,0.75,0.201023,0.828,0.381679,0.666667,0.014599,1.0,0.727273,0.836957,0.011521
4,0.0,0.000007,0.001526,0.00,0.283801,0.910,0.381679,0.333333,0.919708,0.0,0.390909,0.836957,0.003500
5,0.0,0.000008,0.004971,0.00,0.650034,0.520,0.381679,0.333333,0.481752,0.0,0.059091,0.836957,0.000000
6,0.0,0.000008,0.013221,0.00,0.672281,0.780,0.381679,0.333333,0.919708,0.0,0.511364,0.836957,0.011521
7,0.0,0.000009,0.000462,0.75,0.103645,0.000,0.381679,0.333333,0.919708,0.0,0.538636,0.836957,0.011521
8,0.0,0.000009,0.003656,0.00,0.942688,0.022,0.381679,0.666667,0.905109,0.0,0.236364,0.836957,0.001847
9,0.0,0.000009,0.002368,0.25,0.890779,0.504,0.129771,0.666667,0.248175,1.0,0.452273,0.836957,0.011521

### Scaling com algoritmo

In [8]:
dados.columns

Index(['isFraud', 'TransactionDT', 'TransactionAmt', 'ProductCD', 'card1',
       'card2', 'card3', 'card4', 'card5', 'card6', 'addr1', 'addr2', 'dist1'],
      dtype='object')

In [12]:
classe = dados['isFraud']
previsores = dados[["TransactionDT", "TransactionAmt", "ProductCD", "card1", "card2", "card3", "card4", "card5", "card6", "addr1", "addr2", "dist1"]]

In [13]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
previsores = scaler.fit_transform(previsores)

In [15]:
pd.DataFrame(previsores)

,0,1,2,3,4,5,6,7,8,9,10,11
0,-1.578750,-0.442967,-0.505283,-1.462809,0.263135,-0.285167,1.261368,-2.370257,1.735615,0.347343,0.070019,0.000146
1,-1.578735,-0.316804,-0.505283,-1.073368,0.807842,-0.285167,-0.665109,-0.813766,-0.576165,0.399509,0.070019,0.714239
2,-1.578728,-0.354653,-0.505283,1.675782,1.295544,-0.285167,1.261368,-2.005454,-0.576165,1.922775,0.070019,0.000146
3,-1.578727,-0.354653,2.563125,-1.107250,0.959853,-0.285167,1.261368,-2.370257,1.735615,1.338509,0.070019,0.000146
4,-1.578726,-0.358859,-0.505283,-0.813332,1.219538,-0.285167,-0.665109,0.645444,-0.576165,-0.205623,0.070019,-0.349498
...,...,...,...,...,...,...,...,...,...,...,...,...
579460,1.825265,-0.281037,0.517520,-0.838846,0.288470,2.786350,1.261368,0.596804,-0.576165,0.076076,0.070019,0.000146
579461,1.825269,-0.398810,-0.505283,0.106589,-0.870615,-0.285167,1.261368,0.596804,-0.576165,-0.915089,0.070019,0.000146
579462,1.825275,-0.434767,-0.505283,0.431735,1.472890,-0.285167,1.261368,0.596804,-0.576165,-0.633390,0.070019,0.000146
579463,1.825277,-0.072888,-0.505283,-0.427770,0.750837,-0.285167,1.261368,0.596804,-0.576165,0.994209,0.070019,-0.489352
579464,1.825287,0.612389,-0.505283,1.049983,-1.218974,-0.285167,1.261368,-2.370257,1.735615,0.076076,0.070019,0.000146

In [16]:
data.to_csv('base_scaled.csv')